audio_settings:
  default_samplerate: 8000
  default_offset: 0.0
  default_duration: null

directory_settings:
  main_input_directory: "assets/input/"
  main_output_directory: "assets/output/"
  audio_directory: "audio/"
  text_directory: "text/"
  patient_directory: "patients/"
  split_audio_directory: "split_audio/"
  spectrum_audio_directory: "spectrum/"
  waveform_audio_directory: "waveform/"
  fundamental_frequency_audio_directory: "fundfreq/"
  sepformer_output_directory: "SepFormer/"
  diarization_output_directory: "Diarization/"

audio_visualizer_settings:
  waveform: True
  spectrum: True
  mel_spectrogram: True
  fundamental_frequency: True

audio_splitter_settings:
  perform_all: False
  perform_on_ids: [0, 1, 2, 3]
  offset: 0
  duration: 5

separator_settings:
  perform_all: False
  perform_on_ids: [10]

diarization_settings:
  perform_all: False
  perform_on_ids: [9]
  model_output:
    original: True
    sizing: 1
